version: '3'

services:
  front:
    build: './TrashaFront'
    container_name: 'trasha-front'
    ports:
      - '8080:3000'
    environment:
      WDS_SOCKET_PORT: 8080

  back:
    build: './TrashaBack'
    container_name: 'trasha-backend'
    ports:
      - '5000:8080'
    depends_on:
      - database
    environment:
      TS_DIRECTORY: ./

  database:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "trasha_db"
      POSTGRES_USER: "shakalyan"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - ./db_raw_sql/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    restart: always
    expose:
      - '5432'
